version: "3.9"

services:
  api:
    build: .
    container_name: weather-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
  
  db:
    image: postgres:14
    container_name: weather_db
    restart: always
    environment:
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      -"5432:5432"
    volumes:
      -postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data
